# Alert configuration and thresholds
# Adjust values based on network requirements

thresholds:
  signal:
    rssi:
      warning: -70  # dBm
      critical: -80  # dBm
    noise_floor:
      warning: -90  # dBm
      critical: -85  # dBm
    snr:
      warning: 15  # dB
      critical: 10  # dB

  network:
    packet_loss:
      warning: 0.05  # 5%
      critical: 0.10  # 10%
    latency:
      warning: 30  # ms
      critical: 50  # ms
    bandwidth_utilization:
      warning: 0.80  # 80%
      critical: 0.90  # 90%

  system:
    cpu_usage:
      warning: 0.80  # 80%
      critical: 0.90  # 90%
    memory_usage:
      warning: 0.80  # 80%
      critical: 0.90  # 90%
    uptime:
      warning: 3600  # 1 hour in seconds
      critical: 1800  # 30 minutes in seconds

notifications:
  channels:
    slack:
      enabled: true
      rate_limit: 300  # seconds between alerts
      priority:
        warning: "low"
        critical: "high"
    email:
      enabled: true
      rate_limit: 1800  # 30 minutes between alerts
      priority:
        warning: "normal"
        critical: "urgent"
    sms:
      enabled: true
      rate_limit: 3600  # 1 hour between alerts
      priority:
        warning: false  # Don't send SMS for warnings
        critical: true  # Only send SMS for critical alerts

alert_rules:
  - name: "Signal Degradation"
    condition: "rssi < threshold.signal.rssi.warning OR snr < threshold.signal.snr.warning"
    severity: "warning"
    message: "Signal quality degrading on {device_name}"
    
  - name: "High Packet Loss"
    condition: "packet_loss > threshold.network.packet_loss.critical"
    severity: "critical"
    message: "Critical packet loss detected on {device_name}"
    
  - name: "Bandwidth Saturation"
    condition: "bandwidth_utilization > threshold.network.bandwidth_utilization.warning"
    severity: "warning"
    message: "High bandwidth usage on {device_name}"
